apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
spec:  
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: eccbot/istioworker:latest
          imagePullPolicy: Always
          resources: {}